const ROLES = Object.freeze({
  ADMIN: "ADMIN",
  FACULTY: "FACULTY",
  STUDENT: "STUDENT",
  SMARTBOARD: "SMARTBOARD"
});

const OTP_PURPOSES = Object.freeze({
  REGISTRATION: "REGISTRATION",
  SMARTBOARD_LOGIN: "SMARTBOARD_LOGIN",
  PASSWORD_RESET: "PASSWORD_RESET"
});

const SMARTBOARD_SESSION_STATUS = Object.freeze({
  PENDING: "PENDING",
  AUTHORIZED: "AUTHORIZED",
  EXPIRED: "EXPIRED"
});

module.exports = {
  OTP_PURPOSES,
  ROLES,
  SMARTBOARD_SESSION_STATUS
};
